name: Update README with Starter Kits

on:
  push:
    branches:
      - main
      - restructure

permissions:
  contents: write

jobs:
    update-readme:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
    
            -   name: Set up Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'
    
            -   name: Update README with Starter Kits
                run: node update-readme.js
    
            -   name: Commit and push if changed
                run: |
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    
                    # Check if README.md exists and show its content
                    echo "Current README.md content (first few lines):"
                    head README.md
                    
                    # Always add README.md since we're generating it from the template
                    git add README.md
                    
                    # Check for changes in the staging area
                    git status
                    
                    # Force the commit even if git thinks there are no changes
                    git commit --allow-empty -m "Update README with latest starter kits from template"
                    
                    # Force push to ensure README.md is always updated
                    git push --force origin HEAD:${{ github.ref }}


